version: '3.8'

services:
  node-application:
    image: node-application
    build:
      context: .
      dockerfile: ./Dockerfile
      target: node-application
    networks:
      - external-sites
    restart: unless-stopped

  nginx-public-files:
    image: nginx-public-files
    build:
      context: .
      dockerfile: ./Dockerfile
      target: nginx-public-files
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - node-application
    networks:
      - external-sites
    restart: unless-stopped

networks:
  external-sites:
