version: '3.8'

x-args: &args
  args:
    DOCKER_REGISTRY: ${DOCKER_REGISTRY:-}
    DOCKER_ID: ${DOCKER_ID:-}
    BUILD_TAG: ${BUILD_TAG:-local}

services:
  ingress-proxy:
    image: ingress-proxy-production:local
    build:
      context: .
      dockerfile: Production.dockerfile
      <<: *args
      target: ingress-proxy-production
    ports:
      - "80:80"
      - "443:443"
