version: '3.8'

services:
  f4rside-site:
    image: ${dockerId:-johnchase}/f4rside-site:${BUILD_TAG:-latest}
    networks:
      - external-sites
    restart: unless-stopped

  ingress-proxy:
    image: ${dockerId:-johnchase}/ingress-proxy:${BUILD_TAG:-local}
    build:
      context: .
      dockerfile: ./Dockerfile
      target: ingress-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - f4rside-site
    networks:
      - external-sites
    restart: unless-stopped

networks:
  external-sites:
