version: '3.8'

services:
  portfolio-simple:
    image: ${dockerId:-johnchase}/portfolio-simple:${BUILD_TAG:-latest}
    networks:
      - portfolio
    restart: unless-stopped

  portfolio-sql:
    image: ${dockerId:-johnchase}/portfolio-sql:${BUILD_TAG:-latest}
    networks:
      - portfolio
    restart: unless-stopped

  portfolio-template:
    image: ${dockerId:-johnchase}/portfolio-template:${BUILD_TAG:-latest}
    depends_on:
      - portfolio-simple
      - portfolio-sql
    networks:
      - portfolio
    restart: unless-stopped

  portfolio-static:
    image: ${dockerId:-johnchase}/portfolio-static:${BUILD_TAG:-latest}
    networks:
      - portfolio
    restart: unless-stopped

  portfolio-site:
    image: ${dockerId:-johnchase}/portfolio-site:${BUILD_TAG:-latest}
    depends_on:
      - portfolio-template
      - portfolio-static
    networks:
      - portfolio
      - external-sites
    restart: unless-stopped

  f4rside-site:
    image: ${dockerId:-johnchase}/f4rside-site:${BUILD_TAG:-latest}
    networks:
      - external-sites
    restart: unless-stopped

  ingress-proxy:
    image: ingress-proxy-test:local
    build:
      context: .
      dockerfile: Test.dockerfile
      target: ingress-proxy-test
    ports:
      - "80:80"
    depends_on:
      - portfolio-site
      - f4rside-site
    networks:
      - external-sites
    restart: unless-stopped

networks:
  portfolio:
  external-sites:
