version: '3.8'

services:
  f4rside-site:
    image: ${REGISTRY}${REPOSITORY}/f4rside-site:${IMAGE_TAG:-latest}
    deploy:
      replicas: 1
    networks:
      - external-sites

  portfolio-simple:
    image: ${REGISTRY}${REPOSITORY}/portfolio-simple:${IMAGE_TAG:-latest}
    deploy:
      replicas: 1
    networks:
      - portfolio

  portfolio-sql:
    image: ${REGISTRY}${REPOSITORY}/portfolio-sql:${IMAGE_TAG:-latest}
    deploy:
      replicas: 1
    networks:
      - portfolio

  portfolio-template:
    image: ${REGISTRY}${REPOSITORY}/portfolio-template:${IMAGE_TAG:-latest}
    deploy:
      replicas: 1
    depends_on:
      - portfolio-simple
      - portfolio-sql
    networks:
      - portfolio

  portfolio-static:
    image: ${REGISTRY}${REPOSITORY}/portfolio-static:${IMAGE_TAG:-latest}
    deploy:
      replicas: 1
    networks:
      - portfolio

  portfolio-site:
    image: ${REGISTRY}${REPOSITORY}/portfolio-site:${IMAGE_TAG:-latest}
    deploy:
      replicas: 1
    depends_on:
      - portfolio-template
      - portfolio-static
    networks:
      - portfolio
      - external-sites

  ingress-proxy:
    image: ingress-proxy-test:local
    ports:
      - "80:80"
    deploy:
      replicas: 1
    depends_on:
      - portfolio-site
      - f4rside-site
    networks:
      - external-sites

networks:
  portfolio:
  external-sites:
