version: '3.8'

services:
  ingress-proxy:
    image: ${DOCKER_REGISTRY}${DOCKER_REPOSITORY}/ingress-proxy-production:${IMAGE_TAG:-latest}
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - source: f4rside-com-crt-v1
        target: /etc/nginx/certs/f4rside.com.crt
      - source: f4rside-com-key-v1
        target: /etc/nginx/certs/f4rside.com.key
    volumes:
      - /home/pi/letsencrypt:/etc/nginx/letsencrypt

secrets:
  f4rside-com-crt-v1:
    external: true
  f4rside-com-key-v1:
    external: true
