version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    deploy:
      replicas: 1
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
