global:
  scrape_interval:     2m
  evaluation_interval: 2m
  external_labels:
    monitor: 'pi-farm'

scrape_configs:
  # Make Prometheus scrape itself for metrics.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Job for Docker Swarm containers.
#  - job_name: 'dockerswarm'
#    dockerswarm_sd_configs:
#      - host: unix:///var/run/docker.sock
#        role: tasks
#    relabel_configs:
#      # Only keep containers that should be running.
#      - source_labels: [__meta_dockerswarm_task_desired_state]
#        regex: running
#        action: keep

  # Job for Docker containers.
  - job_name: "docker"
    static_configs:
      - targets: ['192.168.1.32:9323', '192.168.1.34:9323', '192.168.1.36:9323', '192.168.1.38:9323', '192.168.1.40:9323', '192.168.1.42:9323']

  - job_name: 'guinea_bot'
    metrics_path: /
    static_configs:
      - targets: ['guinea-bot:8000']

  - job_name: 'f4rside_site'
    static_configs:
      - targets: ['nginx-exporter-f4rside-site:9113']

  - job_name: 'portfolio_map'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['portfolio-map:8001']

  - job_name: 'portfolio_sql'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['portfolio-sql:8002']

  - job_name: 'portfolio_template'
    static_configs:
      - targets: ['portfolio-template:3000']

  - job_name: 'portfolio_static'
    static_configs:
      - targets: ['nginx-exporter-portfolio-static:9113']

  - job_name: 'portfolio_site'
    static_configs:
      - targets: ['nginx-exporter-portfolio-site:9113']

  - job_name: 'ingress_proxy'
    static_configs:
      - targets: ['nginx-exporter-ingress-proxy:9113']
