global:
  scrape_interval:     1m
  evaluation_interval: 1m
  external_labels:
    monitor: 'pi-farm'

scrape_configs:
  # Make Prometheus scrape itself for metrics.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Job for Docker Swarm containers.
#  - job_name: 'dockerswarm'
#    dockerswarm_sd_configs:
#      - host: unix:///var/run/docker.sock
#        role: tasks
#    relabel_configs:
#      # Only keep containers that should be running.
#      - source_labels: [__meta_dockerswarm_task_desired_state]
#        regex: running
#        action: keep

  # Job for Docker containers.
  - job_name: "docker"
    static_configs:
      - targets: ['zeropi:9323', 'onepi:9323', 'twopi:9323', 'threepi:9323', 'fourpi:9323', 'fivepi:9323']

  - job_name: 'guineabot'
    metrics_path: /
    static_configs:
      - targets: ['threepi:8000']
